---
title: p3on
author: p3on
email: p3on@protonmail.com
description: Personal page for collection of commands and projects or configuration on the things I am/was working on.

collections:
  cli-cs:
    output: true
  articles:
    output: true
  snippets:
    output: true

defaults:
  - scope:
      path: '_cli-cs'
    values:
      layout: cli-cs
  - scope:
      path: '_articles'
    values:
      layout: article
  - scope:
      path: '_snippets'
    values:
      layout: snippet

permalink: /:title:none

# Conversion
markdown: Kramdown

highlighter: rouge

kramdown:
  syntax_highlighter: rouge
#  syntax_highlighter_opts: { line_numbers: table }

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

exclude:
  - README.md
  - setup.sh
  - LICENSE