---
title: Config

collections:
  tools:
    output: true
  articles:
    output: true

defaults:
  - scope:
      path: '_tools'
    values:
      layout: tool
  - scope:
      path: '_articles'
    values:
      layout: article
  - scope:
      path: '_coding'
    values:
      layout: coding
  - scope:
      path: '_snippets'
    values:
      layout: snippets

# Conversion
markdown: Kramdown

highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  # syntax_highlighter_opts: { line_numbers: table }

# theme: Minima

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]