---
title: Config

collections:
  cli-cs:
    output: true
  articles:
    output: true
  snippets:
    output: true

defaults:
  - scope:
      path: '_cli-cs'
    values:
      layout: cli-cs
  - scope:
      path: '_articles'
    values:
      layout: article
  - scope:
      path: '_snippets'
    values:
      layout: snippet

permalink: /:title:none

# Conversion
markdown: Kramdown

highlighter: rouge

kramdown:
  syntax_highlighter: rouge
#  syntax_highlighter_opts: { line_numbers: table }

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - setup.sh
  - LICENSE

plugins:
  - jekyll-toc

toc:
  min_level: 1
  max_level: 3
  ordered_list: false